### ISSUE TITLE
Readme update w/ version bump

### ISSUE THREAD

**Issue by XueyanZhang** [uw-pluverse/perses#29]
Instruction for downloading still shows v1.4.
```
wget https://github.com/perses-project/perses/releases/download/v1.4/perses_deploy.jar
java -jar perses_deploy.jar [options]? --test-script <test-script.sh> --input-file <program file>
```

A quick sed cmd can be added to `reducer/perses/scripts/release.py` to bump the version in readme

**Comment by chengniansun** [comment]
Fixed internally by 0fcad862121362435c071c7d86395ff8071cd9ec.

Thanks for catching this type of error.
